Pages/BufferedSingleFileUploadDb.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using EnhancedEbookWebApp.Data;
using EnhancedEbookWebApp.Models;
using EnhancedEbookWebApp.Utilities;
using Microsoft.AspNetCore.Authorization;

namespace EnhancedEbookWebApp.Pages
{
    [Authorize]
    public class BufferedSingleFileUploadDbModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<BufferedSingleFileUploadDbModel> logger;
        private readonly long _fileSizeLimit;
        private readonly string[] _permittedExtensions = { ".epub" };

        public BufferedSingleFileUploadDbModel(AppDbContext context, 
            IConfiguration config, ILogger<BufferedSingleFileUploadDbModel> logger)
        {
            _context = context;
            this.logger = logger;
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        [BindProperty]
        public BufferedSingleFileUploadDb FileUpload { get; set; }

        public string Result { get; private set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostUploadAsync()
        {
            // Perform an initial check to catch FileUpload class
            // attribute violations.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            var formFileContent = 
                await FileHelpers.ProcessFormFile<BufferedSingleFileUploadDb>(
                    FileUpload.FormFile, ModelState, _permittedExtensions, 
                    _fileSizeLimit);

            // Perform a second check to catch ProcessFormFile method
            // violations. If any validation check fails, return to the
            // page.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }


            var file = new Ebook
            {
                Content = formFileContent,
                UntrustedName = FileUpload.FormFile.FileName,
                Title = FileUpload.Title,
                Author = FileUpload.Author,

                Size = FileUpload.FormFile.Length,
                UploadDT = DateTime.UtcNow
            };

            _context.Ebook.Add(file);
            await _context.SaveChangesAsync();

            //logging
            string clientIP = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            logger.LogInformation($"An ebook (id= {file.ID}, title= \"{file.Title}\", author= {file.Author}, filename= {file.UntrustedName})  was added to the database by a client with the following ip address: {clientIP}");


            return RedirectToPage("./Index");
        }
    }

    public class BufferedSingleFileUploadDb
    {
        [Required]
        [Display(Name = "File")]
        public IFormFile FormFile { get; set; }

        [Required]
        [Display(Name = "Title")]
        [StringLength(50, MinimumLength = 0)]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Author")]
        [StringLength(50, MinimumLength = 0)]
        public string Author { get; set; }
    }
}

Pages/DeleteDbFile.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EnhancedEbookWebApp.Data;
using EnhancedEbookWebApp.Models;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace EnhancedEbookWebApp.Pages
{
    [Authorize]
    public class DeleteDbFileModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<DeleteDbFileModel> logger;

        public DeleteDbFileModel(AppDbContext context, ILogger<DeleteDbFileModel> logger)
        {
            _context = context;
            this.logger = logger;
        }

        [BindProperty]
        public Ebook RemoveFile { get; private set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("/Index");
            }

            RemoveFile = await _context.Ebook.SingleOrDefaultAsync(m => m.ID == id);

            if (RemoveFile == null)
            {
                return RedirectToPage("/Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("/Index");
            }

            RemoveFile = await _context.Ebook.FindAsync(id);

            if (RemoveFile != null)
            {
                _context.Ebook.Remove(RemoveFile);
                await _context.SaveChangesAsync();
            }

            //logging
            string clientIP = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            logger.LogInformation($"An ebook (id= {RemoveFile.ID}, title= \"{RemoveFile.Title}\", author= {RemoveFile.Author}, filename= {RemoveFile.UntrustedName})  was removed from the database by a client with the following ip address: {clientIP}");

            return RedirectToPage("/Index");
        }
    }
}

Pages/Ebooks/BufferedSingleFileUploadDb.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using DotNetCoreSqlDb.Models;
using DotNetCoreSqlDb.Utilities;

namespace DotNetCoreSqlDb.Pages.Ebooks
{
    public class BufferedSingleFileUploadDbModel : PageModel
    {
        private readonly MyDatabaseContext _context;
        private readonly long _fileSizeLimit;
        private readonly string[] _permittedExtensions = { ".txt" };

        public BufferedSingleFileUploadDbModel(MyDatabaseContext context, 
            IConfiguration config)
        {
            _context = context;
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        [BindProperty]
        public BufferedSingleFileUploadDb FileUpload { get; set; }

        public string Result { get; private set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostUploadAsync()
        {
            // Perform an initial check to catch FileUpload class
            // attribute violations.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            var formFileContent = 
                await FileHelpers.ProcessFormFile<BufferedSingleFileUploadDb>(
                    FileUpload.FormFile, ModelState, _permittedExtensions, 
                    _fileSizeLimit);

            // Perform a second check to catch ProcessFormFile method
            // violations. If any validation check fails, return to the
            // page.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            // **WARNING!**
            // In the following example, the file is saved without
            // scanning the file's contents. In most production
            // scenarios, an anti-virus/anti-malware scanner API
            // is used on the file before making the file available
            // for download or for use by other systems. 
            // For more information, see the topic that accompanies 
            // this sample.

            var file = new Ebook
            {
                Content = formFileContent, 
                UntrustedName = FileUpload.FormFile.FileName, 
                Title = FileUpload.Title,
                Author = FileUpload.Author,

                Size = FileUpload.FormFile.Length, 
                UploadDT = DateTime.UtcNow
            };

            _context.Ebook.Add(file);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }

    public class BufferedSingleFileUploadDb
    {
        [Required]
        [Display(Name="File")]
        public IFormFile FormFile { get; set; }

        [Display(Name="Title")]
        [StringLength(50, MinimumLength = 0)]
        public string Title { get; set; }

        [Display(Name = "Author")]
        [StringLength(50, MinimumLength = 0)]
        public string Author { get; set; }
    }
}

Pages/Ebooks/DeleteDbFile.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DotNetCoreSqlDb.Data;
using DotNetCoreSqlDb.Models;

namespace DotNetCoreSqlDb.Pages.Ebooks
{
    public class DeleteDbFileModel : PageModel
    {
        private readonly AppDbContext _context;

        public DeleteDbFileModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public AppFile RemoveFile { get; private set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("/Index");
            }

            RemoveFile = await _context.File.SingleOrDefaultAsync(m => m.Id == id);

            if (RemoveFile == null)
            {
                return RedirectToPage("/Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("/Index");
            }

            RemoveFile = await _context.File.FindAsync(id);

            if (RemoveFile != null)
            {
                _context.File.Remove(RemoveFile);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EnhancedEbookWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EnhancedEbookWebApp.Data;
using EnhancedEbookWebApp.Models;

namespace EnhancedEbookWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext _context;

        public IndexModel(AppDbContext context)
        {
            _context = context;
        }

        public IList<Ebook> DatabaseFiles { get; private set; }
        

        public async Task OnGetAsync()
        {
            DatabaseFiles = await _context.Ebook.AsNoTracking().ToListAsync();
            
        }

        public async Task<IActionResult> OnGetDownloadDbAsync(int? id)
        {
            if (id == null)
            {
                return Page();
            }

            var requestFile = await _context.Ebook.SingleOrDefaultAsync(m => m.ID == id);

            if (requestFile == null)
            {
                return Page();
            }

            // Don't display the untrusted file name in the UI. HTML-encode the value.
            return File(requestFile.Content, MediaTypeNames.Application.Octet, WebUtility.HtmlEncode(requestFile.UntrustedName));
        }

        
    }
}

Pages/BufferedSingleFileUploadDb.cshtml
@page
@model BufferedSingleFileUploadDbModel
@{
    ViewData["Title"] = "File Upload";
}

<h1>Upload an .epub File</h1>
<p>Free eBooks can be found at <a href="https://www.gutenberg.org/" target="_blank">Project Gutenberg</a> </p>
<br />


<form enctype="multipart/form-data" method="post">
    <dl>
        <dt>
            <label asp-for="FileUpload.Title"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.Title" type="text" />
            <span asp-validation-for="FileUpload.Title"></span>
        </dd>
        <dt>
            <label asp-for="FileUpload.Author"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.Author" type="text" />
            <span asp-validation-for="FileUpload.Author"></span>
        </dd>
        <dt>
            <label asp-for="FileUpload.FormFile"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.FormFile" type="file" />
            <span asp-validation-for="FileUpload.FormFile"></span>
        </dd>
    </dl>
    <input asp-page-handler="Upload" class="btn btn-primary" type="submit" value="Upload" />
</form>

<p class="result">
    @Model.Result
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/DeleteDbFile.cshtml
@page "{id:int}"
@model DeleteDbFileModel
@{
    ViewData["Title"] = "Delete File";
}

<h1>Delete File</h1>

<p>Are you sure you want to delete this file?</p>

<dl>
    <dt>
        @Html.DisplayNameFor(model => model.RemoveFile.UntrustedName)
    </dt>
    <dd>
        @Model.RemoveFile.UntrustedName
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RemoveFile.Title)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RemoveFile.Title)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RemoveFile.Author)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RemoveFile.Author)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RemoveFile.Size)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RemoveFile.Size)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RemoveFile.UploadDT)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RemoveFile.UploadDT)
    </dd>
</dl>

<form method="post">
    <input type="hidden" asp-for="RemoveFile.ID" />
    <input type="submit" value="Delete" class="btn btn-primary" />
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Ebook List";
}

    <h1>Enhanced Ebook Manager</h1>

<p>
    <a asp-page="/BufferedSingleFileUploadDb">Upload an .epub File</a>
</p>

@if (Model.DatabaseFiles.Count == 0)
{
    <p>
        No files are available.
    </p>
}
else
{
    <table>
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.DatabaseFiles[0].UntrustedName) /
                    @Html.DisplayNameFor(model => model.DatabaseFiles[0].Title)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.DatabaseFiles[0].Author)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.DatabaseFiles[0].UploadDT)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.DatabaseFiles[0].Size)
                </th>
                <th class="text-center">
                    <code>FileStreamResult</code> from database
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ebook in Model.DatabaseFiles)
            {
                <tr>
                    <td>
                        <a asp-page="./DeleteDbFile" asp-route-id="@ebook.ID">Delete</a>
                    </td>
                    <td>
                        <b>@ebook.UntrustedName</b><br>
                        @Html.DisplayFor(modelItem => ebook.Title)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => ebook.Author)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => ebook.UploadDT)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => ebook.Size)
                    </td>
                    <td class="text-center">
                        <a asp-page-handler="DownloadDb" asp-route-id="@ebook.ID">Download</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}